services:
  db:
    container_name: surrealdb
    image: surrealdb/surrealdb:latest-dev
    ports:
      - "8000:8000"
    # temporary use root as user
    user: root
    volumes:
      - ./data:/data
    command: start file:/data/mydatabase.db
    networks:
      - surrealdb
networks:
  surrealdb:
    driver: bridge